name: xiflutter
description: Flutter Starterkit
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  url_launcher: 5.0.3
  nb_utils: 3.2.2
  google_fonts: 1.1.0
  animations: 1.1.2
  intl: 0.16.1
  http: 0.12.2
  html: 0.14.0+3
  share: 0.6.5
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_vector_icons: 0.2.1
  package_info: 0.4.3

  flutter_statusbarcolor: 0.2.3
  simple_animations: 1.3.8
  snaplist: 0.1.8
  flutter_svg: 0.18.1
  flutter_slidable: 0.5.7
  flutter_staggered_grid_view: 0.3.2
  flutter_staggered_animations: 0.1.2

  liquid_swipe: 1.5.0
  lipsum: 1.0.1
  clippy_flutter: 1.1.1
  flutter_tags: ^0.4.8
  flutter_reaction_button: ^1.0.1
  lottie: ^0.6.0
  date_utils: ^0.1.0+3
  cached_network_image: ^2.3.1
  flutter_localizations:
    sdk: flutter

  # Dynamic wiget need thease plugin
  logging: ^0.11.3+2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner: ^1.9.0
  change_app_package_name: ^0.1.2

flutter:

  uses-material-design: true

  assets:

    - assets/
    - images/app/


  fonts:
    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

